# Generated by Django 4.2.5 on 2024-04-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='genres',
            new_name='filmwork_genres',
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='persons',
            new_name='filmwork_persons',
        ),
    ]
