# docker-compose.yml

version: '3.9'
services:
  django:
    volumes:
      - ./movies_admin/staticfiles:/opt/app/staticfiles
      - ./.env:/opt/app/.env
      - ./logs/nginx/json-logs.json:/opt/app/logs/nginx/json-logs.json
      - ./sqlite_to_postgres:/opt/app/sqlite_to_postgres
    build: ./movies_admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elk_default


  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./movies_admin/staticfiles:/movies_admin/staticfiles:ro
    depends_on:
      - django
    ports:
      - ${NGINX_INTERNAL_PORT}:${NGINX_EXTERNAL_PORT}
    networks:
      - elk_default


  postgres:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./schema_design/movies_database.ddl:/schema_design/movies_database.ddl:ro
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - elk_default


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_EXTERNAL_PORT}:${ES_INTERNAL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
    networks:
      - elk_default

  etl:
    volumes:
      - ./postgres_to_es/logs:/opt/app/logs
      - ./postgres_to_es/storage.json:/opt/app/storage.json
      - ./.env:/opt/app/.env
    build: ./postgres_to_es
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk_default
  
  filebeat:
    image: elastic/filebeat:8.10.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk_default

networks:
  elk_default:
    name: elk_name